name: reflection_factory
description: Allows Dart reflection with an easy approach, even for third-party classes, using code generation portable for all Dart platforms.
version: 1.1.1
homepage: https://github.com/gmpassos/reflection_factory

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  build: ^2.2.1
  analyzer: ^3.3.1
  dart_style: ^2.2.1
  meta: ^1.7.0
  mime: ^1.0.1
  base_codecs: ^1.0.1
  pub_semver: ^2.0.0
  path: ^1.8.1
  collection: ^1.16.0
  yaml: ^3.1.0
  source_span: ^1.8.2

dev_dependencies:
  build_runner: ^2.1.1
  build_test: ^2.1.3
  lints: ^1.0.1
  pubspec: ^2.0.1
  data_serializer: ^1.0.3
  dependency_validator: ^3.1.0
  test: ^1.16.0
  coverage: ^1.0.3
