name: reflection_factory
description: Allows Dart reflection with an easy approach, even for third-party classes, using code generation portable for all Dart platforms.
version: 2.1.5
homepage: https://github.com/gmpassos/reflection_factory

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  build: ^2.4.0
  analyzer: ^5.13.0
  dart_style: ^2.3.1
  meta: ^1.9.1
  mime: ^1.0.4
  base_codecs: ^1.0.1
  pub_semver: ^2.1.4
  path: ^1.8.3
  collection: ^1.17.1
  yaml: ^3.1.2
  source_span: ^1.10.0

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.6
  lints: ^2.0.1
  pubspec: ^2.3.0
  data_serializer: ^1.0.7
  dependency_validator: ^3.2.2
  test: ^1.24.3
  coverage: ^1.6.3
  benchmark: ^0.3.0
