name: reflection_factory
description: Allows Dart reflection with an easy approach, even for third-party classes, using code generation portable for all Dart platforms.
version: 1.2.12
homepage: https://github.com/gmpassos/reflection_factory

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  build: ^2.3.0
  analyzer: ^4.6.0
  dart_style: ^2.2.3
  meta: ^1.8.0
  mime: ^1.0.2
  base_codecs: ^1.0.1
  pub_semver: ^2.1.1
  path: ^1.8.2
  collection: ^1.16.0
  yaml: ^3.1.1
  source_span: ^1.9.1

dev_dependencies:
  build_runner: ^2.2.0
  build_test: ^2.1.5
  lints: ^2.0.0
  pubspec: ^2.3.0
  data_serializer: ^1.0.7
  dependency_validator: ^3.2.2
  test: ^1.21.4
  coverage: ^1.5.0
