name: reflection_factory
description: Allows Dart reflection with an easy approach, even for third-party classes, using code generation portable for all Dart platforms.
version: 1.0.8
homepage: https://github.com/gmpassos/reflection_factory

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  build: ^2.1.0
  analyzer: ^2.1.0
  dart_style: ^2.0.3
  meta: ^1.7.0
  pub_semver: ^2.0.0
  path: ^1.8.0
  collection: ^1.15.0
  yaml: ^3.1.0
  source_span: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.1
  build_test: ^2.1.3
  lints: ^1.0.1
  dependency_validator: ^3.1.0
  test: ^1.16.0
  test_cov: ^1.0.1
