name: reflection_factory
description: Allows Dart reflection with an easy approach, even for third-party classes, using code generation portable for all Dart platforms.
version: 1.2.19
homepage: https://github.com/gmpassos/reflection_factory

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  build: ^2.3.1
  analyzer: ^4.7.0
  dart_style: ^2.2.4
  meta: ^1.8.0
  mime: ^1.0.3
  base_codecs: ^1.0.1
  pub_semver: ^2.1.3
  path: ^1.8.3
  collection: ^1.16.0
  yaml: ^3.1.1
  source_span: ^1.9.1

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.5
  lints: ^2.0.1
  pubspec: ^2.3.0
  data_serializer: ^1.0.7
  dependency_validator: ^3.2.2
  test: ^1.22.1
  coverage: ^1.6.1
